## Configuration file for the IMI

## General
isAWS: true
RunName: "Test_Permian_1week"
UseSlurm: true

## Period of interest
StartDate: 20180501
EndDate: 20180508
SpinupMonths: 1

## Region of interest
##   These lat/lon bounds will only be used if CreateStateVectorFile: true
LonMin: -105
LonMax: -103
LatMin: 31
LatMax: 33
##   Select nesting window (NA, EU, or AS)
REGION: "NA"

## State vector
BufferDeg: 5
nBufferClusters: 8
LandThreshold: 0.25
##   Option for the IMI to automatically create the state vector file:
CreateStateVectorFile: true

## Custom state vector
##   If using a custom/pre-generated state vector file, provide the path:
StateVectorFile: {optional/path/to/statevector_ncfile}
##   To create a custom state vector file from a shape file, follow three steps:
##   1. Provide path to shapefile and lat/lon bounds for the inversion domain
ShapeFile: {optional/path/to/shapefile}
LonMinCustomStateVector: -110
LonMaxCustomStateVector: -100
LatMinCustomStateVector: 25
LatMaxCustomStateVector: 35
##   2. Open and run the statevector_from_shapefile.ipynb Jupyter notebook
##   3. When complete, define StateVectorFile: {path/to/statevector_ncfile} above

## Inversion
PriorError: 0.5
ObsError: 15
Gamma: 0.25

## Grid
##   Res & Met are "0.25x0.3125" and "geosfp", or "0.5x0.625" and "merra2"
Res: "0.25x0.3125"
Met: "geosfp"
##   Other grid settings
HalfPolar: "F"
Levs: "47"
NestedGrid: "T"
Buffer: "3 3 3 3"

## Setup modules
##   Turn on/off different steps in setting up the inversion 
SetupTemplateRundir: true
SetupSpinupRun: false
SetupJacobianRuns: false
SetupInversion: false
SetupPosteriorRun: false

## Run modules
##   Turn on/off different steps in performing the inversion
RunSetup: true
DoSpinup: false
DoJacobian: false
DoInversion: false
DoPosterior: false

## IMI preview
DoPreview: true
DOFSThreshold: 0

## ======================================================================
## Specific to Harvard's Cannon cluster
## ======================================================================

## Compute resources to request
nCPUs: 16
partition: "huce_cascade"