import os
from pathlib import Path
import yaml
import subprocess
import numpy as np
import xarray as xr
import sparselt.esmf
import sparselt.xr
from src.utilities.regrid_state_vector_file import(
    get_gridspec_prefix,
)

def create_regrid_weights_ESMF(config):
    RunDirs=f"{os.path.expandvars(config['OutputPath']) }/{config['RunName']}"
    CSgridDir=f"{RunDirs}/CS_grids"
    
    if config['UseGCHP']:
        dst_CS_RES = config['CS_RES']
        dst_STRETCH_GRID = config['STRETCH_GRID']
        dst_STRETCH_FACTOR = config['STRETCH_FACTOR']
        dst_TARGET_LAT = config['TARGET_LAT']
        dst_TARGET_LON = config['TARGET_LON']
        if dst_TARGET_LON > 180:
            dst_TARGET_LON = dst_TARGET_LON - 360
        dst_prefix = get_gridspec_prefix(
            dst_CS_RES, 
            dst_STRETCH_GRID,
            dst_STRETCH_FACTOR,
            dst_TARGET_LAT,
            dst_TARGET_LON,
        )
        dst_grid_path = f"{dst_prefix}_gridspec.nc"
        if not os.path.exists(os.path.join(CSgridDir, dst_grid_path)):
            subprocess.run([
                'gridspec-create', 'sgcs',
                '-s', f"{dst_STRETCH_FACTOR}",
                '-t', f"{dst_TARGET_LAT}", f"{dst_TARGET_LON}", f"{dst_CS_RES}"
                ],
                check=True, cwd=CSgridDir,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,)
    # create C360 grid if it does not exist
    src_CS_RES = 360
    src_prefix = get_gridspec_prefix(src_CS_RES, False)
    src_grid_path = f"{src_prefix}_gridspec.nc"
    if not os.path.exists(os.path.join(CSgridDir, src_grid_path)):
        subprocess.run([
            'gridspec-create', 'gcs',
            f'{src_CS_RES}'
            ],
            check=True, cwd=CSgridDir,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,)
    
    # create regrid weights if it does not exist
    if config['UseGCHP']:
        regrid_weight_fpath = f"regrid_weights_c{src_CS_RES}_to_c{dst_CS_RES}_s{dst_STRETCH_FACTOR:.1f}_{dst_TARGET_LAT:.1f}N_{dst_TARGET_LON:.1f}E_conserve.nc"
        if not os.path.exists(os.path.join(CSgridDir, regrid_weight_fpath)):
            subprocess.run([
                "ESMF_RegridWeightGen",
                "-s", src_grid_path,
                "-d", dst_grid_path,
                "-m", "conserve",
                "--ignore_unmapped",
                "-w", regrid_weight_fpath
                ], 
                check=True, cwd=CSgridDir, 
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL, 
            )
        return os.path.join(CSgridDir, regrid_weight_fpath)

def regrid_c360_prior_emis_to_C36S10(config):
    print("Regridding C360 HemcoPriorEmis to C36S10 grid...")
    ref_CS_RES = 360
    dst_CS_RES = config['CS_RES']
    dst_STRETCH_GRID = config['STRETCH_GRID']
    dst_STRETCH_FACTOR = config['STRETCH_FACTOR']
    dst_TARGET_LAT = config['TARGET_LAT']
    dst_TARGET_LON = config['TARGET_LON']
    if dst_TARGET_LON > 180:
        dst_TARGET_LON = dst_TARGET_LON - 360
    RunDirs=f"{os.path.expandvars(config['OutputPath']) }/{config['RunName']}"
    prior_emis_dir = os.path.join(RunDirs, "hemco_prior_emis/OutputDir")
    ref_prior_emis_dir = config["ReferencePriorEmisDir"]
    # get the list of all files in ref_prior_emis_dir
    files = list(Path(ref_prior_emis_dir).glob("*.nc")) + list(Path(ref_prior_emis_dir).glob("*.nc4"))
    files = [str(p) for p in files]
    for i in range(len(files)):
        file = files[i]
        print(f"Regridding {os.path.basename(file)} ({i+1}/{len(files)})")
        
        file_path = os.path.join(prior_emis_dir, os.path.basename(file))
        if os.path.exists(file_path):
            print(f"File {file_path} already exists. Skipping.")
            continue
        ref_prior_fpath = os.path.join(ref_prior_emis_dir, os.path.basename(file))
        if not os.path.exists(ref_prior_fpath):
            print(f"Reference file {ref_prior_fpath} does not exist. Skipping.")
            continue
        # regridding using sparselt
        src_ds = xr.open_dataset(ref_prior_fpath)
        regrid_weights_fpath = create_regrid_weights_ESMF(config)
        # Create a linear transformer object from an ESMF weights file
        transform = sparselt.esmf.load_weights(
            regrid_weights_fpath,                              # Generated by ESMF_RegridWeightGen
            input_dims=[('nf', 'Ydim', 'Xdim'), (6, ref_CS_RES, ref_CS_RES)],  # applied along input dimensions
            output_dims=[('nf', 'Ydim', 'Xdim'), (6, dst_CS_RES, dst_CS_RES)],           # result dimensions
        )

        # Apply the transform to ds
        ds = sparselt.xr.apply(transform, src_ds)
        # add coordinates and attributes
        CSgridDir=f"{RunDirs}/CS_grids"
        grid_fpath = os.path.join(CSgridDir, f"grids.c{dst_CS_RES}.nc")
        grid_ds = xr.open_dataset(grid_fpath)
        ds = ds.assign_coords({
            "lats": grid_ds["lats"],
            "lons": grid_ds["lons"],
        })
        ds['corner_lats'] = grid_ds['corner_lats'].copy(deep=True)
        ds['corner_lons'] = grid_ds['corner_lons'].copy(deep=True)
        
        # add emis attributes
        emis_vars = [var for var in ds.data_vars if var.startswith("Emis")]
        for var in emis_vars:
            ds[var].attrs = src_ds[var].attrs
        if dst_STRETCH_GRID:
            ds.attrs['STRETCH_FACTOR'] = np.float32(dst_STRETCH_FACTOR)
            ds.attrs['TARGET_LAT'] = np.float32(dst_TARGET_LAT)
            ds.attrs['TARGET_LON'] = np.float32(dst_TARGET_LON)
        
        ds.to_netcdf(
            file_path,
            encoding={
                v: {"zlib": True, "complevel": 1} for v in ds.data_vars
            },
        )
        
    print("Done regridding C360 HemcoPriorEmis to C36S10 grid...")


if __name__ == "__main__":
    import sys

    config_path = sys.argv[1]
    config = yaml.load(open(config_path), Loader=yaml.FullLoader)
    regrid_c360_prior_emis_to_C36S10(config)